// flow-typed signature: b8e6af0aa8969b4cdf7734583936386d
// flow-typed version: <<STUB>>/babel-exclude-ignore_v^1.0.0/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-exclude-ignore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-exclude-ignore' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-exclude-ignore/register' {
  declare module.exports: any;
}

declare module 'babel-exclude-ignore/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-exclude-ignore/index' {
  declare module.exports: $Exports<'babel-exclude-ignore'>;
}
declare module 'babel-exclude-ignore/index.js' {
  declare module.exports: $Exports<'babel-exclude-ignore'>;
}
declare module 'babel-exclude-ignore/register.js' {
  declare module.exports: $Exports<'babel-exclude-ignore/register'>;
}
declare module 'babel-exclude-ignore/test.js' {
  declare module.exports: $Exports<'babel-exclude-ignore/test'>;
}
